### PR TITLE
Add icon button for Mail and Github with Github username on Github icon button.

### PR DESCRIPTION
**Pull request by Gilliash**
Please inform me if this doesn't meet your requirements. I will check again, thank you.

### CODE REVIEW

**Comment by ashutosh887** [comment]
Can we use LinkButton for the task? @Gilliash 

`mail` should be `href="mailto:{mail}"` and for GitHub button, a new tab should open for GitHub Profile

**Comment by Gilliash** [comment]
Oh, about that, I saw someone had been assigned to do that and I think they
already did it,

Vào CN, 29 thg 10, 2023 vào lúc 18:50 Ashutosh Jha <
***@***.***> đã viết:

**Comment by ashutosh887** [comment]
Let's do that as well here

**Comment by Gilliash** [comment]
Oke, I'll find solution


Vào CN, 29 thg 10, 2023 vào lúc 18:57 Ashutosh Jha <
***@***.***> đã viết:

**Comment by Gilliash** [comment]
I want to be clear, we need those github buttons to link to the github
accounts right?


Vào CN, 29 thg 10, 2023 vào lúc 18:59 Khang Nguyễn ***@***.***>
đã viết:

**Comment by ashutosh887** [comment]
Yes @Gilliash

**Comment by ashutosh887** [comment]
Use `LinkButton` component @Gilliash

**Comment by Gilliash** [comment]
Ah sorry, my bad

Vào 19:35, CN, 29 Th10, 2023 Ashutosh Jha ***@***.***> đã
viết:

**Comment by Gilliash** [comment]
I used the Link component, is this enough?

**Comment by Gilliash** [comment]
Hi mate I changed to using Link component, please check it if you have
time, UwU

Vào CN, 29 thg 10, 2023 vào lúc 19:36 Khang Nguyễn ***@***.***>
đã viết:

**Comment by Gilliash** [comment]
Are the button link component meet the requirement, mate?

Vào 20:00, CN, 29 Th10, 2023 Khang Nguyễn ***@***.***> đã viết:

**Comment by ashutosh887** [comment]
There's already a `LinkButton` Component that I'd created @Gilliash 
Use that
Why are you using others


https://github.com/ashutosh887/hacktober-2023/pull/63#issuecomment-1784094046

**Comment by ashutosh887** [comment]
hacktober-2023/src/components/common/LinkButton.tsx

**Comment by Gilliash** [comment]
Oh, my bad for not noticing that, I'll change it right away


Vào Th 3, 31 thg 10, 2023 vào lúc 00:14 Ashutosh Jha <
***@***.***> đã viết:

**Comment by Gilliash** [comment]
Hi mate, I just need to replace only the github button, not with the email?

Vào Th 3, 31 thg 10, 2023 vào lúc 00:31 Khang Nguyễn ***@***.***>
đã viết:

**Comment by Gilliash** [comment]
Hi mate, I used LinkButton component as you asked, I'm not sure about the
email so I left the link blank. If something's wrong, please let me know!

Vào Th 3, 31 thg 10, 2023 vào lúc 00:42 Khang Nguyễn ***@***.***>
đã viết:

**Comment by Gilliash** [comment]
Everything's oke?

Vào 01:02, T.3, 31 Th10, 2023 Khang Nguyễn ***@***.***> đã viết:

**Comment by ashutosh887** [comment]
Add link for email as `mailto:someone@something.com` 

like this @Gilliash

**Comment by Gilliash** [comment]
It's done, mate!

Vào 18:42, T.4, 1 Th11, 2023 Ashutosh Jha ***@***.***> đã
viết:

**Comment by Gilliash** [comment]
Is the email link alright, mate?

Vào 20:33, T.4, 1 Th11, 2023 Khang Nguyễn ***@***.***> đã viết:

**Comment by ashutosh887** [comment]
Bro you had to use the real `email` in place of `someone@something.com`
Please change 🙂

**Comment by ashutosh887** [comment]
@Gilliash

**Comment by Gilliash** [comment]
Lmao, I'm so sorry for this :))

Vào 19:41, T.5, 2 Th11, 2023 Ashutosh Jha ***@***.***> đã
viết:

**Comment by Gilliash** [comment]
Is it right?

Vào 19:46, T.5, 2 Th11, 2023 Khang Nguyễn ***@***.***> đã viết:

**Comment by Gilliash** [comment]
@ashutosh887

Vào 19:50, T.5, 2 Th11, 2023 Khang Nguyễn ***@***.***> đã viết:

**Review by ashutosh887 — APPROVED** [review]

**Comment by ashutosh887** [comment]
Amazing Work @Gilliash

**Comment by Gilliash** [comment]
Thanks mate! Thank you for giving me a chance to work with this issue! Best
wishes!

Vào CN, 5 thg 11, 2023 vào lúc 00:29 Ashutosh Jha <
***@***.***> đã viết:

**Pull request merged**
